### Exercício 1 - Considere o vetor [1, 2, 3, 4, 5], construa um novo vetor com três elementos 0 (zero) entre cada elemento do vetor.

In [1]:
import numpy as np

In [176]:
arr = np.array([1, 2, 3, 4, 5], dtype=int)
arr

array([1, 2, 3, 4, 5])

In [179]:
zeros = np.zeros(len(arr) + (len(arr) - 1) * (3), dtype=int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [180]:
len(zeros)

17

In [154]:
zeros[::4] = arr 
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

### Exercício 2 - Crie uma matriz quadrada de 8 X 8 e preencha com o padrão de tabuleiro de xadrez, utilizando 0 (zero) para casas brancas e 1 (um) para casas pretas

In [2]:
zeros = np.zeros((8, 8), dtype=int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
zeros[1::2, ::2] = zeros[::2, 1::2] = 1
zeros

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Exercício 3 - Dado um array de 2 dimensões, como trocar 2 linhas entre si?

In [104]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
A[[0, 1]] = A[[1, 0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [106]:
A[[2, 3]] = A[[3, 2]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

### Exercício 4 - Utilizando o mesmo array do exercício anterior, como trocar 2 colunas entre si?

In [107]:
A[:,[2, 3]] = A[:,[3, 2]]
A

array([[ 5,  6,  8,  7,  9],
       [ 0,  1,  3,  2,  4],
       [15, 16, 18, 17, 19],
       [10, 11, 13, 12, 14],
       [20, 21, 23, 22, 24]])

### Exercício 5 - Dado o array [1, 2, 3] criar o array [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [26]:
a = np.array([1,2,3])

In [29]:
np.tile(a, [4, 1])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Exercício 6 - Dado o array [1, 2, 3] criar o array [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [67]:
a = np.array([1,2,3])

In [73]:
np.repeat(a, 3).reshape(3, 3)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### Exercício 7 - Dado o array [4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 88], obtenha todos os itens que estão entre 35 e 55.

In [144]:
arr = np.array([4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 55, 88])
arr

array([ 4, 95, 37, 64, 42, 19, 38, 46, 83, 48, 67, 98, 21, 10, 55, 88])

In [145]:
arr[np.where((arr >= 35) & (arr <= 55))]

array([37, 42, 38, 46, 48, 55])

In [146]:
arr[np.where(np.logical_and(arr >= 35, arr <= 55))]

array([37, 42, 38, 46, 48, 55])

In [147]:
arr[(arr >= 35) & (arr <= 55)]

array([37, 42, 38, 46, 48, 55])

### Exercicio 8 - Considere um array com 100 elementos inteiros iniciando em 0. Dado um número randômico positivo e flutuante, descubra qual o elemento do array, mais próximo desse número.

In [19]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
f = np.random.uniform(0,100)
f

47.70491856433783

In [29]:
x = np.abs(arr-f)
x

array([47.70491856, 46.70491856, 45.70491856, 44.70491856, 43.70491856,
       42.70491856, 41.70491856, 40.70491856, 39.70491856, 38.70491856,
       37.70491856, 36.70491856, 35.70491856, 34.70491856, 33.70491856,
       32.70491856, 31.70491856, 30.70491856, 29.70491856, 28.70491856,
       27.70491856, 26.70491856, 25.70491856, 24.70491856, 23.70491856,
       22.70491856, 21.70491856, 20.70491856, 19.70491856, 18.70491856,
       17.70491856, 16.70491856, 15.70491856, 14.70491856, 13.70491856,
       12.70491856, 11.70491856, 10.70491856,  9.70491856,  8.70491856,
        7.70491856,  6.70491856,  5.70491856,  4.70491856,  3.70491856,
        2.70491856,  1.70491856,  0.70491856,  0.29508144,  1.29508144,
        2.29508144,  3.29508144,  4.29508144,  5.29508144,  6.29508144,
        7.29508144,  8.29508144,  9.29508144, 10.29508144, 11.29508144,
       12.29508144, 13.29508144, 14.29508144, 15.29508144, 16.29508144,
       17.29508144, 18.29508144, 19.29508144, 20.29508144, 21.29

In [30]:
x.argmin()

48

In [31]:
arr[(np.abs(arr - f)).argmin()]

48

### Exercicio 9 - Dado um array, substitua todos os valores inferiores a 10 por 10 e todos os valores superiores a 30 por 30.

In [215]:
np.random.seed(100)
arr = np.random.uniform(1, 50, 30)
arr

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])

In [220]:
arr.min()

10.0

In [221]:
arr.max()

30.0

In [218]:
arr = np.clip(arr, a_min=10, a_max=30)

In [219]:
arr

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])