In [1]:
import numpy as np

In [3]:
np.random.rand(5,3) * 3

array([[1.70885391, 0.72253567, 2.10372713],
       [0.99110133, 1.76658495, 2.66477732],
       [0.17679909, 0.5089535 , 0.68551623],
       [1.76791999, 0.33458466, 2.52456671],
       [2.91602737, 1.61756564, 1.38442721]])

In [5]:
np.random.randn(5,2)

array([[-0.38803217, -0.10114152],
       [ 0.94728324, -1.18418286],
       [ 0.15510795,  0.38608392],
       [ 0.63365618,  0.20480437],
       [-0.56589612, -2.6992855 ]])

In [28]:
np.random.randint(1,6)

1

In [29]:
np.random.randint(1,6, size = (5,3))

array([[3, 4, 2],
       [3, 5, 3],
       [5, 3, 5],
       [2, 5, 5],
       [5, 2, 2]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(5) * 3

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [33]:
a = np.random.rand(10)
a

array([0.01582454, 0.03279975, 0.37409049, 0.38632137, 0.37031311,
       0.49641955, 0.05184359, 0.33115932, 0.72597949, 0.96773435])

In [39]:
a = a.reshape(5,2)
a

array([[0.01582454, 0.03279975],
       [0.37409049, 0.38632137],
       [0.37031311, 0.49641955],
       [0.05184359, 0.33115932],
       [0.72597949, 0.96773435]])

In [40]:
a.max()

0.9677343469886417

In [41]:
a.min()

0.01582454313330728

In [42]:
a.shape

(5, 2)

In [43]:
a.mean()

0.375248555917306

In [44]:
a.std()

0.290150608400624

In [45]:
a.sum()

3.75248555917306

In [48]:
a.sum(axis = 0)

array([1.53805122, 2.21443434])

In [49]:
a.sum(axis = 1)

array([0.04862429, 0.76041186, 0.86673266, 0.38300291, 1.69371383])

In [75]:
a = np.array([1,2,3,5,6,7,8])
a

array([1, 2, 3, 5, 6, 7, 8])

In [77]:
np.insert(a,3,4) # inseriu na posicao 3 o valor 4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
np.insert(a,(3,4,5),(33,44,55)) # inseriu nas posicoes 3,4,5 os valores 33,44,55 nas posicoes originais da matriz

array([ 1,  2,  3, 33,  5, 44,  6, 55,  7,  8])

In [80]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
np.insert(a, [1], [[6],[7],[8]], axis=1) # inseriu na coluna 1

array([[ 0,  6,  1,  2,  3],
       [ 4,  7,  5,  6,  7],
       [ 8,  8,  9, 10, 11]])

In [60]:
np.delete(a, 3) # deletou posicao 3

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
np.delete(a, np.s_[2:4]) # deletou posicoes 2 a 4-nao incluso

array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
np.delete(a, 2, 1) # deletou coluna 1

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [72]:
np.delete(a, 2, 0) # deletou linha 2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
np.delete(a, np.s_[1:3], 1) # deletou coluna 1 e 2

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [83]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,7,8,9,10,11])
np.add(a,b)

array([ 7,  9, 11, 13, 15, 17])

In [84]:
a = np.array([1,2,3,4,5,6])
b = np.array([6])
np.add(a,b)

array([ 7,  8,  9, 10, 11, 12])

In [91]:
a = np.arange(30).reshape(2,3,5)
b = np.arange(15).reshape(3,5)
np.add(a,b) # broadcasting

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]],

       [[15, 17, 19, 21, 23],
        [25, 27, 29, 31, 33],
        [35, 37, 39, 41, 43]]])

In [92]:
a = np.arange(12).reshape(3,2,2)
b = np.arange(4).reshape(2,2)
np.add(a,b) # broadcasting

array([[[ 0,  2],
        [ 4,  6]],

       [[ 4,  6],
        [ 8, 10]],

       [[ 8, 10],
        [12, 14]]])

In [96]:
a = np.arange(10)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
a[2],a[5]

(4, 10)

In [99]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
a[1,2] # linha 1 coluna 2

7

In [103]:
a[1,2],a[2,2] # linha 1 coluna 2 em tupla com linha 2 coluna 2

(7, 12)

In [104]:
a[1,2] = 99
a # replace no index

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
a[3:,3:] # da linha 3 ao final e da coluna 4 ao final

array([[18, 19],
       [23, 24]])

In [108]:
a[:,2]  # todas as linhas da coluna 2

array([ 2, 99, 12, 17, 22])

In [109]:
a[2::2,::2] # iniciando na linha 2 até o fim pulando 2 / iniciando da coluna 0 até o fim pulando 2

array([[10, 12, 14],
       [20, 22, 24]])

In [110]:
a % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [111]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [131]:
a[a % 2 == 0] = 99
a

array([[99,  1, 99,  3, 99],
       [ 5, 99,  7, 99,  9],
       [99, 11, 99, 13, 99],
       [15, 99, 17, 99, 19],
       [99, 21, 99, 23, 99]])

In [132]:
m1 = a % 3 == 0
a[m1]

array([99, 99,  3, 99, 99, 99,  9, 99, 99, 99, 15, 99, 99, 99, 21, 99, 99])

In [133]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [134]:
m1 = a % 2 == 0
m2 = a % 5 == 0
a[m1 & m2] 

array([ 0, 10, 20])

In [135]:
a[np.where(np.logical_and(a % 2 == 0, a % 10 == 0))]

array([ 0, 10, 20])