## Lista de Exercícios 01

In [558]:
import numpy as np
import pandas as pd

### 1.) Complete uma tabela com um conjunto de 12 números entre 1 e 50. Utilizando os dados criados por você, calcular:
**• Média<br>
• Moda<br>
• Mediana<br>
• Variância amostral<br>
• Desvio padrão amostral<br>
• Coeficiente de variação<br><br>
*Regras:<br>
• Pelo menos um valor deve estar repetido.<br>
• O conjunto de dados deve apresentar, pelo menos, 6 valores únicos.<br>
• NÃO É PERMITIDO escolher todos os números iguais.<br>
• Trabalhos com os mesmos dados serão considerados inválidos.***

In [630]:
def create_array():
    
    return np.random.randint(1,51,12)

In [631]:
def write_array(new_file, array_lst):
    
    with open('students.txt', 'w') as txtFile:
        
        for row in array_lst:            
            txtFile.write(" ".join(map(str, row)))
            txtFile.write("\n")

In [632]:
def test_array(arr):

    unique = np.unique(arr)
    
    m = np.zeros_like(arr, dtype=bool)
    m[np.unique(arr, return_index=True)[1]] = True
    repeat = arr[~m]
    
    if len(repeat) == 0:
        return False
    
    elif len(unique) < 6:
        return False
    
    elif len(repeat) == len(a)-1:
        return False
    
    else:
        return True

In [633]:
def create_txt():
    
    array_lst = []
    
    while len(array_lst) < 50:
    
        arr = create_array()
        
        if test_array(arr) == True:
            array_lst.append(arr)
            
    # check for equal arrays
    L = {array.tostring(): array for array in array_lst}
    if len(L.values()) < 50:
        create_txt()

    write_array('students.txt', array_lst)

In [634]:
def exercicio():
    
    create_txt()
    
    with open('students.txt') as f:
        
        for line in f:
            arr = np.fromstring(line, dtype=int, sep=' ')
            
            print(arr)
            print('média: {:.4f}'.format(np.mean(arr)))
            print('moda: {}'.format(pd.Series(arr).mode()))
            print('mediana: {:.4f}'.format(np.median(arr)))
            print('variância amostral: {:.4f}'.format(np.std(arr, ddof=1)**2))
            print('desvio padrão amostral: {:.4f}'.format(np.std(arr, ddof=1)))
            print('coeficiente de variação: {:.4f}\n'.format(np.std(arr, ddof=1)/np.mean(arr)))

In [635]:
exercicio()

[47 21 15  7 29 25 45  9 28 41 37 47]
média: 29.2500
moda: 0    47
dtype: int64
mediana: 28.5000
variância amostral: 206.5682
desvio padrão amostral: 14.3725
coeficiente de variação: 0.4914

[ 5 29 29 38 50 50 21 20 23 31 33 23]
média: 29.3333
moda: 0    23
1    29
2    50
dtype: int64
mediana: 29.0000
variância amostral: 161.3333
desvio padrão amostral: 12.7017
coeficiente de variação: 0.4330

[15 23  1  5  1 38  3 30 27 23 40 43]
média: 20.7500
moda: 0     1
1    23
dtype: int64
mediana: 23.0000
variância amostral: 243.1136
desvio padrão amostral: 15.5921
coeficiente de variação: 0.7514

[44  3  8 38 27 41 36 33 12 44 15 29]
média: 27.5000
moda: 0    44
dtype: int64
mediana: 31.0000
variância amostral: 210.8182
desvio padrão amostral: 14.5196
coeficiente de variação: 0.5280

[18  7 18 46 29 46 43 31  8 18 35  6]
média: 25.4167
moda: 0    18
dtype: int64
mediana: 23.5000
variância amostral: 225.1742
desvio padrão amostral: 15.0058
coeficiente de variação: 0.5904

[13  7 41 30  6 21 41