## Lista de Exercícios 01

In [1]:
import numpy as np
import pandas as pd

### 1.) Faça uma análise estatística descritiva da base de dados ozone.data.txt, localizada na pasta db, da disciplina

In [10]:
df = pd.read_csv('ozone.data.txt', sep="\t")
df

rad  temp  wind  ozone
0    190    67   7.4     41
1    118    72   8.0     36
2    149    74  12.6     12
3    313    62  11.5     18
4    299    65   8.6     23
..   ...   ...   ...    ...
106   20    63  16.6     14
107  193    70   6.9     30
108  191    75  14.3     14
109  131    76   8.0     18
110  223    68  11.5     20

[111 rows x 4 columns]

In [11]:
# analise descritiva built-in do pandas
df.describe()

rad        temp        wind       ozone
count  111.000000  111.000000  111.000000  111.000000
mean   184.801802   77.792793    9.938739   42.099099
std     91.152302    9.529969    3.559218   33.275969
min      7.000000   57.000000    2.300000    1.000000
25%    113.500000   71.000000    7.400000   18.000000
50%    207.000000   79.000000    9.700000   31.000000
75%    255.500000   84.500000   11.500000   62.000000
max    334.000000   97.000000   20.700000  168.000000

In [12]:
# moda
df.mode()

rad  temp  wind  ozone
0  238.0  81.0  10.3   23.0
1    NaN   NaN  11.5    NaN

In [13]:
# mediana
df.median()

rad      207.0
temp      79.0
wind       9.7
ozone     31.0
dtype: float64

In [14]:
# variancia
df.var()

rad      8308.742179
temp       90.820311
wind       12.668031
ozone    1107.290090
dtype: float64

In [20]:
# diferenca entre o maior e o menor valor do intervalo
df.max()-df.min()

rad      327.0
temp      40.0
wind      18.4
ozone    167.0
dtype: float64

### 2.) Complete uma tabela com um conjunto de 12 números entre 1 e 50. Utilizando os dados criados por você, calcular:
**• Média<br>
• Moda<br>
• Mediana<br>
• Variância amostral<br>
• Desvio padrão amostral<br>
• Coeficiente de variação<br><br>
*Regras:<br>
• Pelo menos um valor deve estar repetido.<br>
• O conjunto de dados deve apresentar, pelo menos, 6 valores únicos.<br>
• NÃO É PERMITIDO escolher todos os números iguais.<br>
• Trabalhos com os mesmos dados serão considerados inválidos.***

In [630]:
def create_array():
    # cria um array de 12 inteiros entre 1 e 50
    return np.random.randint(1,51,12)

In [631]:
def write_array(new_file, array_lst):
    
    with open('students.txt', 'w') as txtFile:
        # escrever cada array de 12 inteiros em uma nova linha
        for row in array_lst:            
            txtFile.write(" ".join(map(str, row)))
            txtFile.write("\n")

In [632]:
def test_array(arr):
    # verificacao de unicos
    unique = np.unique(arr)
    
    # verificacao de repetidos
    m = np.zeros_like(arr, dtype=bool)
    m[np.unique(arr, return_index=True)[1]] = True
    repeat = arr[~m]
    
    # filtrar se nao ha duplicados
    if len(repeat) == 0:
        return False
    
    # filtrar se nao ha 6 unicos
    elif len(unique) < 6:
        return False
    
    # filtrar se todos sao iguais
    elif len(repeat) == len(a)-1:
        return False
    
    else:
        return True

In [633]:
def create_txt():
    
    array_lst = []
    
    # repetir ate ter 50 linhas
    while len(array_lst) < 50:
    
        arr = create_array()
        
        if test_array(arr) == True:
            array_lst.append(arr)
            
    # filtrar por eventuais arrays identicos e repetir caso verdadeiro
    L = {array.tostring(): array for array in array_lst}
    if len(L.values()) < 50:
        create_txt()
    
    # chamar a funcao para escrever a lista de arrays
    write_array('students.txt', array_lst)

In [634]:
def exercicio():
    
    create_txt()
    
    with open('students.txt') as f:
        
        # realizar a analise em cada linha do .txt
        for line in f:
            # convertendo o .txt em array do pandas
            arr = np.fromstring(line, dtype=int, sep=' ')
            
            # printando a analise estatistica descritiva
            print(arr)
            print('média: {:.4f}'.format(np.mean(arr)))
            print('moda: {}'.format(pd.Series(arr).mode()))
            print('mediana: {:.4f}'.format(np.median(arr)))
            print('variância amostral: {:.4f}'.format(np.std(arr, ddof=1)**2))
            print('desvio padrão amostral: {:.4f}'.format(np.std(arr, ddof=1)))
            print('coeficiente de variação: {:.4f}\n'.format(np.std(arr, ddof=1)/np.mean(arr)))

In [635]:
exercicio()

[47 21 15  7 29 25 45  9 28 41 37 47]
média: 29.2500
moda: 0    47
dtype: int64
mediana: 28.5000
variância amostral: 206.5682
desvio padrão amostral: 14.3725
coeficiente de variação: 0.4914

[ 5 29 29 38 50 50 21 20 23 31 33 23]
média: 29.3333
moda: 0    23
1    29
2    50
dtype: int64
mediana: 29.0000
variância amostral: 161.3333
desvio padrão amostral: 12.7017
coeficiente de variação: 0.4330

[15 23  1  5  1 38  3 30 27 23 40 43]
média: 20.7500
moda: 0     1
1    23
dtype: int64
mediana: 23.0000
variância amostral: 243.1136
desvio padrão amostral: 15.5921
coeficiente de variação: 0.7514

[44  3  8 38 27 41 36 33 12 44 15 29]
média: 27.5000
moda: 0    44
dtype: int64
mediana: 31.0000
variância amostral: 210.8182
desvio padrão amostral: 14.5196
coeficiente de variação: 0.5280

[18  7 18 46 29 46 43 31  8 18 35  6]
média: 25.4167
moda: 0    18
dtype: int64
mediana: 23.5000
variância amostral: 225.1742
desvio padrão amostral: 15.0058
coeficiente de variação: 0.5904

[13  7 41 30  6 21 41