In [3]:
import numpy as np

## 1 - Crie um vetor com 10 elementos 0.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

## 2 - Crie um vetor com 10 elementos 0 e inicialize o quinto elemento com o valor 1.

In [4]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
```

## 3 - Crie um vetor com valores em sequencia de 10 à 49.

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])
```

## 4 - Crie um vetor com valores inteiros de 50 à 0.

In [11]:
np.arange(50,-1,-1,dtype = int)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```


## 5 - Crie um vetor com valores inteiros de 0 à 49 em seguida inverta a ordem do vetor.

In [10]:
a = np.arange(0,50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
       
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```

## 6 - Crie uma matriz 3 x 3 com valores de 1 à 9.

In [12]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

## 7 - Dada o vetor [1, 3, 0, 3, 0, 3, 2, 0, 1, 0], descubra os índices dos elementos diferentes de zero.

In [13]:
a = np.array([1, 3, 0, 3, 0, 3, 2, 0, 1, 0])
np.nonzero(a)
#np.where(a != 0)

(array([0, 1, 3, 5, 6, 8]),)

```
array([0, 1, 3, 5, 6, 8], dtype=int64)
```

## 8 - Crie uma matriz 3 x 3 x 3 com números aleatórios.

In [30]:
np.random.rand(27).reshape(3,3,3)

array([[[0.83004943, 0.26050545, 0.13088821],
        [0.35264212, 0.18041783, 0.45793185],
        [0.24992796, 0.53148342, 0.99233279]],

       [[0.05311367, 0.042028  , 0.89074753],
        [0.62822678, 0.36964376, 0.95533196],
        [0.99297717, 0.12924412, 0.97620444]],

       [[0.82687754, 0.94983664, 0.8847242 ],
        [0.03780585, 0.57956255, 0.89517558],
        [0.05693272, 0.79445589, 0.26611303]]])

Exemplo:
```
array([[[0.61286554, 0.74921735, 0.61223858],
        [0.96047489, 0.65628431, 0.79342544],
        [0.70941175, 0.98583943, 0.00318382]],

       [[0.85867772, 0.93941609, 0.30006033],
        [0.79160418, 0.0865738 , 0.69892442],
        [0.33265707, 0.25932833, 0.11447914]],

       [[0.24026643, 0.23737787, 0.04470459],
        [0.11646793, 0.32991814, 0.85027852],
        [0.25262905, 0.1805445 , 0.40050341]]])
```

## 9 - Crie um vetor de tamanho 10 com números aleatórios em ordenados em ordem crescente.

In [15]:
a = np.random.rand(10)
a

array([0.82396652, 0.78853141, 0.96145752, 0.69805448, 0.85048892,
       0.97770729, 0.3287451 , 0.61064067, 0.7475537 , 0.07299929])

In [16]:
np.sort(a)

array([0.07299929, 0.3287451 , 0.61064067, 0.69805448, 0.7475537 ,
       0.78853141, 0.82396652, 0.85048892, 0.96145752, 0.97770729])

Exemplo:
```
array([0.56239709, 0.36663249, 0.24432617, 0.43788321, 0.89709646,
       0.58901959, 0.26398762, 0.82502151, 0.3666227 , 0.47548132])
       
array([0.24432617, 0.26398762, 0.3666227 , 0.36663249, 0.43788321,
       0.47548132, 0.56239709, 0.58901959, 0.82502151, 0.89709646])
```