In [1]:
import numpy as np

## Exercício 1

Matriz Identidade

Seja M uma matriz quadrada de ordem n. A matriz M é chamada de Matriz Identidade de ordem n (indicada por In) quando os elementos da diagonal principal são todos iguais a 1 e os elementos restantes são iguais a zero.

**Desenvolva** uma função que retorne a matriz identidade de dimensão n.

Exemplo de matriz identidade de dimensão 3x3:
```
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
```

Exemplo de matriz identidade de dimensão 5x5:
```
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
```    


In [119]:
def identidade(n):
    a = np.zeros(n*n, dtype=int).reshape(n,n)
    for i in range(0,n):
        a[i,i] = 1
    return a

In [123]:
def identidade1(n):
    return np.array([[1 if i == j else 0 for j in range (n)] for i in range(n)])

In [120]:
identidade(4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [124]:
identidade1(4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## Exercício 2

Considere os arrays a e b, descubra os índices dos elementos com o mesmo valor.

In [126]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [127]:
np.where(a == b)

(array([1, 3, 5, 7]),)

## Exercício 3

Crie um array de 2 dimensões (5 X 3) contendo números aleatórios decimais entre 5 e 10.

In [76]:
np.random.randint(5,10, size = (5,3)) + np.random.random((5,3))

array([[9.6501421 , 9.15627105, 8.51050746],
       [6.97970919, 9.90572871, 5.98319815],
       [8.50013172, 5.80328351, 7.73751449],
       [5.8816557 , 8.3563149 , 8.97618533],
       [9.4940212 , 7.35143926, 6.27106405]])

In [128]:
np.random.uniform(5,10, size = (5,3))

array([[5.63327119, 5.39493936, 6.55676567],
       [8.16191794, 8.49679462, 8.20982474],
       [9.6001189 , 6.49438177, 7.84372767],
       [5.89312162, 7.66286851, 8.23345735],
       [5.71032688, 7.90694481, 7.39594968]])

## Exercício 4

Dado o array a, efetue a divisão do menor valor pelo maior valor de cada linha.

In [130]:
np.random.seed(100)
a = np.random.randint(1,10, [5,4])
a

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5]])

In [131]:
np.array([a[0].min()/a[0].max(),
a[1].min()/a[1].max(),
a[2].min()/a[2].max(),
a[3].min()/a[3].max(),
a[4].min()/a[4].max()]).reshape(5,1)

array([[0.44444444],
       [0.125     ],
       [0.5       ],
       [0.11111111],
       [0.14285714]])

In [133]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1).reshape(5,1)

array([[0.44444444],
       [0.125     ],
       [0.5       ],
       [0.11111111],
       [0.14285714]])

## Exercício 5

Elimine os NAN do array a.

In [135]:
a = np.array([[1, np.nan, 3], [np.nan, 5, 6], [7, 8, np.nan]])
a

array([[ 1., nan,  3.],
       [nan,  5.,  6.],
       [ 7.,  8., nan]])

In [137]:
a[~np.isnan(a)] # ~ inversão de lógica

array([1., 3., 5., 6., 7., 8.])

## Exercício 6

Dado o array a de 2 dimensões e o array b de uma dimensão apenas. Subtraia o array b do array a, de forma que cada elemento do array b subtraia a __linha__ correspondente do array a.

In [138]:
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
a

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [139]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [114]:
np.array([a[0]-b[0],
a[1]-b[1],
a[2]-b[2]])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [145]:
a - b.reshape(-1,1) # -1 deixa livre para preencher até dar certo

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])